name: "Build Fedora images"

on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches:
      - main
    paths:
      - 'shared/*'
      - 'scripts/*'
      - 'build/*'
      - '.github/workflows/common-build.yml'
      - '.github/workflows/common-signing.yml'
  push:
    branches:
      - main
    paths:
      - 'shared/*'
      - 'scripts/*'
      - 'build/*'
      - '.github/workflows/common-build.yml'
      - '.github/workflows/common-signing.yml'
  workflow_dispatch:
    inputs:
      push:
        description: Push built images to registry
        required: false
        type: boolean
        default: false
      make_iso:
        description: Build ISO
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - title: Fedora Kinoite (Customized)
            base_image: fedora-kinoite
            final_image: qt-fedora-kinoite
            variant: kinoite
            description: Customized image of Fedora Kinoite
            licenses: MIT
          - title: Fedora Silverblue (Customized)
            base_image: fedora-silverblue
            final_image: qt-fedora-silverblue
            variant: silverblue
            description: Customized image of Fedora Silverblue
            licenses: MIT

    uses: ./.github/workflows/common-build.yml
    permissions:
      contents: read
      packages: write
    with:
      registry: ghcr.io/${{ github.repository_owner }}
      base_image: ${{ matrix.base_image }}
      final_image: ${{ matrix.final_image }}
      variant: ${{ matrix.variant }}
      description: ${{ matrix.description }}
      title: ${{ matrix.title }}
      licenses: ${{ matrix.licenses }}
      push: ${{ inputs.push || ( github.event_name != 'pull_request' && github.ref == 'refs/heads/main' ) }}
      make_iso: ${{ inputs.make_iso || false }}
    secrets: inherit
