name: "Build staging"

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      base_image:
        required: true
        type: string
      final_image:
        required: true
        type: string
      variant:
        required: true
        type: string
      description:
        required: false
        type: string
        default: Customized image of Fedora
      title:
        required: false
        type: string
        default: Fedora
      licenses:
        required: false
        type: string
        default: MIT
      push:
        required: false
        type: boolean
        default: false
      make_iso:
        required: false
        type: boolean
        default: false

jobs:
  build-image:
    uses: ./.github/workflows/common-build-image.yml
    permissions:
      contents: read
      packages: write
    with:
      registry: ${{ inputs.registry }}
      base_image: ${{ inputs.base_image }}
      final_image: ${{ inputs.final_image }}
      variant: ${{ inputs.variant }}
      description: ${{ inputs.description }}
      title: ${{ inputs.title }}
      licenses: ${{ inputs.licenses }}
      push: ${{ inputs.push }}
    secrets: inherit

  build-iso:
    uses: ./.github/workflows/common-build-iso.yml
    needs: [build-image]
    if: inputs.push && inputs.make_iso
    with:
      image_name: ${{ inputs.final_image }}
      image_repo: ${{ inputs.registry }}
      image_tag: ${{ needs.build-image.outputs.major_version }}
      version: ${{ needs.build-image.outputs.major_version }}
      variant: ${{ inputs.variant }}
      iso_name: ${{ inputs.final_image }}-${{ needs.build-image.outputs.major_version }}.iso
    secrets: inherit